import { useState, useMemo, useEffect } from 'preact/hooks'

// Data is loaded dynamically from the JSON file generated by the scraper pipeline

function formatCurrency(value) {
  if (!value) return 'N/A'
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0
  }).format(value)
}

function formatDate(dateStr) {
  if (!dateStr) return 'TBD'
  return dateStr
}

function PropertyCard({ property }) {
  // Use zillow_price from real data (fallback to zillow_estimate for compatibility)
  const marketPrice = property.zillow_price || property.zillow_estimate
  const discountEstimate = marketPrice ? Math.round(marketPrice * 0.85) : null

  return (
    <div className="property-card">
      <div className="card-header">
        <span className="case-number">{property.case_number}</span>
        <span className="status-badge foreclosure">Foreclosure</span>
      </div>

      <div className="property-address">{property.property_street}</div>
      <div className="property-city">
        {property.property_city}, {property.property_state} {property.property_zip}
      </div>

      {marketPrice && (
        <>
          <div className="property-details">
            <div className="detail">
              <div className="detail-value">{property.zillow_bedrooms || '-'}</div>
              <div className="detail-label">Beds</div>
            </div>
            <div className="detail">
              <div className="detail-value">{property.zillow_bathrooms || '-'}</div>
              <div className="detail-label">Baths</div>
            </div>
            <div className="detail">
              <div className="detail-value">{property.zillow_sqft ? property.zillow_sqft.toLocaleString() : '-'}</div>
              <div className="detail-label">Sq Ft</div>
            </div>
          </div>

          <div className="price-section">
            <div className="price-main">
              <div className="price-value">{formatCurrency(discountEstimate)}</div>
              <div className="price-label">Est. Foreclosure Price (~15% below market)</div>
            </div>
            <div className="price-estimate">
              <div className="estimate-value">{formatCurrency(marketPrice)}</div>
              <div className="price-label">Zillow Price</div>
            </div>
          </div>
        </>
      )}

      <div className="parties-section">
        <div className="party">
          <div>
            <div className="party-role">Plaintiff (Lender)</div>
            <div className="party-name">{property.plaintiff_name}</div>
          </div>
          {property.plaintiff_attorney_name && (
            <div className="party-attorney">
              <div className="attorney-name">{property.plaintiff_attorney_name}</div>
              <div className="attorney-phone">{property.plaintiff_attorney_phone}</div>
            </div>
          )}
        </div>

        <div className="party">
          <div>
            <div className="party-role">Defendant (Owner)</div>
            <div className="party-name">{property.defendant_full_name}</div>
          </div>
          {property.defendant_attorney_name && (
            <div className="party-attorney">
              <div className="attorney-name">{property.defendant_attorney_name}</div>
              <div className="attorney-phone">{property.defendant_attorney_phone}</div>
            </div>
          )}
        </div>
      </div>

      <div className="filing-info">
        <span>Filed: {formatDate(property.filing_date)}</span>
        {property.hearing_date && <span>Hearing: {formatDate(property.hearing_date)}</span>}
        {property.zillow_year_built && <span>Built: {property.zillow_year_built}</span>}
      </div>
    </div>
  )
}

export function App() {
  const [searchTerm, setSearchTerm] = useState('')
  const [cityFilter, setCityFilter] = useState('all')
  const [foreclosureData, setForeclosureData] = useState([])
  const [loading, setLoading] = useState(true)
  const [lastUpdated, setLastUpdated] = useState(null)

  // Load data from JSON file on mount
  useEffect(() => {
    fetch('./foreclosures_enriched.json')
      .then(res => res.json())
      .then(data => {
        setForeclosureData(data)
        // Get the most recent scraped_at timestamp
        if (data.length > 0) {
          const dates = data.map(d => d.scraped_at).filter(Boolean).sort()
          if (dates.length > 0) {
            setLastUpdated(new Date(dates[dates.length - 1]).toLocaleDateString())
          }
        }
        setLoading(false)
      })
      .catch(err => {
        console.error('Failed to load foreclosure data:', err)
        setLoading(false)
      })
  }, [])

  const cities = useMemo(() => {
    const uniqueCities = [...new Set(foreclosureData.map(p => p.property_city).filter(Boolean))]
    return uniqueCities.sort()
  }, [foreclosureData])

  const filteredData = useMemo(() => {
    return foreclosureData.filter(property => {
      const matchesSearch = searchTerm === '' ||
        (property.property_street || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        (property.defendant_full_name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        (property.plaintiff_name || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
        (property.case_number || '').toLowerCase().includes(searchTerm.toLowerCase())

      const matchesCity = cityFilter === 'all' || property.property_city === cityFilter

      return matchesSearch && matchesCity
    })
  }, [searchTerm, cityFilter, foreclosureData])

  const totalValue = useMemo(() => {
    return foreclosureData.reduce((sum, p) => sum + (p.zillow_price || p.zillow_estimate || 0), 0)
  }, [foreclosureData])

  if (loading) {
    return (
      <div className="app">
        <header className="header">
          <h1>York County SC Foreclosure Monitor</h1>
          <p className="subtitle">Loading foreclosure data...</p>
        </header>
      </div>
    )
  }

  return (
    <div className="app">
      <header className="header">
        <h1>York County SC Foreclosure Monitor</h1>
        <p className="subtitle">Live foreclosure case data scraped from SC Courts Public Index</p>

        <div className="stats">
          <div className="stat">
            <div className="stat-value">{foreclosureData.length}</div>
            <div className="stat-label">Active Cases</div>
          </div>
          <div className="stat">
            <div className="stat-value">{formatCurrency(totalValue)}</div>
            <div className="stat-label">Total Est. Value</div>
          </div>
          <div className="stat">
            <div className="stat-value">{cities.length}</div>
            <div className="stat-label">Cities</div>
          </div>
        </div>
      </header>

      <div className="filters">
        <input
          type="text"
          className="search-box"
          placeholder="Search by address, name, or case number..."
          value={searchTerm}
          onInput={(e) => setSearchTerm(e.target.value)}
        />

        <button
          className={`filter-btn ${cityFilter === 'all' ? 'active' : ''}`}
          onClick={() => setCityFilter('all')}
        >
          All Cities
        </button>

        {cities.map(city => (
          <button
            key={city}
            className={`filter-btn ${cityFilter === city ? 'active' : ''}`}
            onClick={() => setCityFilter(city)}
          >
            {city}
          </button>
        ))}
      </div>

      {filteredData.length > 0 ? (
        <div className="cards-grid">
          {filteredData.map(property => (
            <PropertyCard key={property.case_number} property={property} />
          ))}
        </div>
      ) : (
        <div className="no-results">
          <p>No foreclosures found matching your criteria.</p>
        </div>
      )}

      <footer className="footer">
        <p>
          Data sourced from <a href="https://publicindex.sccourts.org/york/courtrosters/" target="_blank" rel="noopener">SC Courts Public Index</a> with property data from <a href="https://www.zillow.com" target="_blank" rel="noopener">Zillow</a>
        </p>
        <p>
          Data scraped using anti-bot bypass techniques (TLS fingerprinting, nodriver). Last updated: {lastUpdated || 'N/A'}
        </p>
        <p style={{ marginTop: '0.5rem' }}>
          <a href="https://github.com/tachyurgy/foreclosure-scraper" target="_blank" rel="noopener">View Source on GitHub</a> — Built to demonstrate advanced web scraping techniques
        </p>
      </footer>
    </div>
  )
}
